### PR TITLE
kdudka

### PR DESCRIPTION
**Pull request by kdudka**
fix for https://bugzilla.redhat.com/857875

### CODE REVIEW

**Comment by p** [comment]
Hey,

Do you have any test code to go with these changes?

**Comment by kdudka** [comment]
I used a pycurl-independent test to check the python-to-C int/long casts:

https://bugzilla.redhat.com/attachment.cgi?id=703527

... will try to prepare a pycurl test.

**Comment by kdudka** [comment]
I will resubmit this with the test-case and rebased against latest upstream.

**Comment by p** [comment]
Great, thanks!

Have a look at the following test:

https://github.com/p/pycurl/blob/travis/tests/socket_open_test.py - checks that the callback has in fact been called

The simplest possible test is probably https://github.com/p/pycurl/blob/travis/tests/write_to_stringio_test.py.

**Pull request closed without merging**
