### PR TITLE
kdudka

### PR DESCRIPTION
**Pull request by kdudka**

### CODE REVIEW

**Comment by p** [comment]
Hey,

These changes look good but do you have a bug report or a mailing list topic where they were discussed?

**Comment by kdudka** [comment]
One of them is taken from the corresponding Fedora package, originally applied in 2010:

http://pkgs.fedoraproject.org/cgit/python-pycurl.git/commit/?id=ac3344cf

The other one is based on the following review of a recent Fedora bug:

https://bugzilla.redhat.com/896025#c5

**Comment by p** [comment]
Awesome, thanks.

**Comment by p** [comment]
When I run the internals test with this PR applied I get:

<pre>
sandbox@reactor p % python tests/test_internals.py
Python 2.7.3 (default, Feb  5 2013, 03:41:15) 
[GCC 4.2.1 20070831 patched [FreeBSD]]
PycURL libcurl/7.24.0 OpenSSL/0.9.8x zlib/1.2.7 (compiled against 0x71800)
PycURL version info (3, '7.24.0', 464896, 'amd64-portbld-freebsd9.1', 33308, 'OpenSSL/0.9.8x', 0, '1.2.7', ('dict', 'file', 'ftp', 'ftps', 'gopher', 'http', 'https', 'imap', 'imaps', 'pop3', 'pop3s', 'rtsp', 'smtp', 'smtps', 'telnet', 'tftp'), None, 0, None)
  /usr/local/lib/python2.7/site-packages/pycurl.so, compiled Feb  8 2013 17:06:04
gc: collecting generation 2...
gc: objects in each generation: 0 0 4033
gc: done, 0.0032s elapsed.
Tracked objects: 4033
gc: collecting generation 2...
gc: objects in each generation: 0 0 4033
gc: collectable <pycurl.Curl 0x8015fbf20>
gc: collectable <pycurl.CurlMulti 0x801758820>
gc: collectable <dict 0x8019b8520>
gc: collectable <dict 0x8019b8660>
gc: done, 4 unreachable, 0 uncollectable, 0.0037s elapsed.
Tracked objects: 4029
Fatal Python error: deallocating None
zsh: abort (core dumped)  python tests/test_internals.py
</pre>

Is that supposed to happen?

Also, could you move the global `int res` commit into its own pull request? I think that one can be merged.

**Comment by p** [comment]
Tried this on a linux box I have, same result:

<pre>
Unpacking python-pycurl (from .../python-pycurl_7.19.0-3+b1_i386.deb) ...
Setting up python-pycurl (7.19.0-3+b1) ...
Processing triggers for python-support ...
vps# su - sandbox                 
sandbox@vps:~$ python
Python 2.6.6 (r266:84292, Dec 27 2010, 00:02:40) 
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycurl
>>> for i in xrange(100000):
...  c = pycurl.Curl()
...  c.reset()
... 
Fatal Python error: deallocating None
Aborted
</pre>

**Comment by p** [comment]
Oops, I noticed in the freebsd failure I was testing against the system pycurl. Test passes against the one built from repo.

**Comment by kdudka** [comment]
Thank you for checking it!  The failure actually confirms that the test covers a bug that used to exist, which is cool!

**Pull request merged**
