### PR TITLE
add the GLOBAL_ACK_EINTR constant to the list of exported symbols

### PR DESCRIPTION
**Pull request by kdudka**
... if built against a new enough version of libcurl

Signed-off-by: Kamil Dudka kdudka@redhat.com

### CODE REVIEW

**Comment by p** [comment]
A test can be added checking that:
1. GLOBAL_ACK_EINTR is defined when libcurl >= 7.30.0 is used.
2. It is an accepted flag.

**Comment by p** [comment]
According to http://curl.haxx.se/download.html the most recent release is 7.29. When is 7.30 expected to be released?

**Comment by kdudka** [comment]
The most recent plan I am aware of is April 10th:

http://permalink.gmane.org/gmane.comp.web.curl.library/38601

Sorry for being slow in responses.  I will get back to pycurl when I return from vacation (the end of March).

**Comment by p** [comment]
No worries, there is plenty of other work to be done.

I need to investigate what version development trees of libcurl claim to be.

**Comment by kdudka** [comment]
Sorry for the delay.  I have added a test-case for this and rebased the branch against the latest upstream.

**Comment by p** [comment]
Thanks!

**Pull request merged**
